version: '3'
services: 
    app:
        container_name: cappers
        restart: always
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/
       